---
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: spark-operator
spec:
  chart:
    git: git@github.com:GoogleCloudPlatform/spark-on-k8s-operator.git
    ref: master
    path: charts/spark-operator-chart
